import { Theme } from '../types/theming';

import {
  primary,
  primaryDark,
  secondary,
  secondaryDark,
  secondaryDarkA,
  neutral,
  neutralDark,
  utility,
  utilityDark,
  dangerDark,
  warningDark,
  successDark,
  success,
  danger,
  warning,
  info,
  infoDark,
  primaryDarkA,
  primaryA,
  secondaryA,
} from './global/colors';

import {
  PrimaryDarkButton,
  SecondaryDarkButton,
  TertiaryDarkButton,
  SuccessDarkButton,
  WarningDarkButton,
  DangerDarkButton,
  PrimaryLightButton,
  SecondaryLightButton,
  TertiaryLightButton,
  SuccessLightButton,
  WarningLightButton,
  DangerLightButton,
} from './atoms/button';
import { AppSwitcherDark, AppSwitcherLight } from './organisms/app-switcher';
import { DropdownDark, DropdownLight } from './molecules/dropdown';

export const defaultDarkTheme: Theme = {
  themeName: 'dark',
  transparent: 'transparent',
  rootBgColor: neutralDark.step1,
  rootFontColor: secondaryDark.step12,
  primary: { ...primaryDark },
  primaryA: { ...primaryDarkA },
  secondary: { ...secondaryDark },
  secondaryA: { ...secondaryDarkA },
  success: { ...successDark },
  warning: { ...warningDark },
  danger: { ...dangerDark },
  info: { ...infoDark },
  neutral: { ...neutralDark },
  text: {
    primary: secondaryDark.step12,
    placeholder: secondaryDark.step11,
    disabled: neutral.step10,
  },
  tint: {
    secondary: secondaryDark.step11,
  },
  // *** ATOMS *** //
  button: {
    primary: PrimaryDarkButton,
    secondary: SecondaryDarkButton,
    tertiary: TertiaryDarkButton,
    success: SuccessDarkButton,
    warning: WarningDarkButton,
    danger: DangerDarkButton,
  },
  // *** MOLECULES *** //
  dropdown: DropdownDark,
  dialog: {
    bg: secondaryDark.step2,
    color: secondaryDark.step12,
  },
  toast: {
    bg: secondaryDark.step3,
    border: secondaryDark.step5,
    successText: utilityDark.successText,
    successBg: utilityDark.successBg,
    successBorder: utilityDark.successBorder,
    warningText: utilityDark.warningText,
    warningBg: utilityDark.warningBg,
    warningBorder: utilityDark.warningBorder,
    errorText: utilityDark.dangerText,
    errorBg: utilityDark.dangerBg,
    errorBorder: utilityDark.dangerBorder,
    icon: {
      default: utilityDark.success,
      success: utilityDark.success,
      warning: utilityDark.warning,
      error: utilityDark.danger,
    },
  },
  // *** ORGANISMS *** //
  navTabs: {
    bg: secondaryDark.step2,
    navLinkColor: secondaryDark.step9,
    navLinkHoverColor: secondaryDark.step10,
    navLinkSelected: secondaryDark.step12,
    navLinkDropdownText: secondaryDark.step12,
    hoverNavLinkDropdownBg: secondaryDark.step4,
    hoverNavLinkDropdownBorder: secondaryDark.step8,
    activeNavLinkDropdownBg: secondaryDark.step9,
    activeNavLinkDropdownBorder: secondaryDark.step6,
  },
  appSwitcher: AppSwitcherDark,
};

export const defaultLightTheme: Theme = {
  themeName: 'light',
  transparent: 'transparent',
  rootBgColor: secondary.step1,
  rootFontColor: secondary.step12,
  primary: { ...primary },
  primaryA: { ...primaryA },
  secondary: { ...secondary },
  secondaryA: { ...secondaryA },
  success: { ...success },
  warning: { ...warning },
  danger: { ...danger },
  info: { ...info },
  neutral: { ...neutral },
  text: {
    primary: secondary.step12,
    placeholder: secondary.step11,
    disabled: neutral.step10,
  },
  tint: {
    secondary: secondary.step11,
  },
  // *** ATOMS *** //
  button: {
    primary: PrimaryLightButton,
    secondary: SecondaryLightButton,
    tertiary: TertiaryLightButton,
    success: SuccessLightButton,
    warning: WarningLightButton,
    danger: DangerLightButton,
  },
  // *** MOLECULES *** //
  dropdown: DropdownLight,
  dialog: {
    bg: secondary.step2,
    color: secondary.step12,
  },
  toast: {
    bg: secondary.step3,
    border: secondary.step5,
    successText: utility.successText,
    successBg: utility.successBg,
    successBorder: utility.successBorder,
    warningText: utility.warningText,
    warningBg: utility.warningBg,
    warningBorder: utility.warningBorder,
    errorText: utility.dangerText,
    errorBg: utility.dangerBg,
    errorBorder: utility.dangerBorder,
    icon: {
      default: utility.success,
      success: utility.success,
      warning: utility.warning,
      error: utility.danger,
    },
  },
  // *** ORGANISMS *** //
  navTabs: {
    bg: secondary.step2,
    navLinkColor: secondary.step9,
    navLinkHoverColor: secondary.step10,
    navLinkSelected: secondary.step12,
    navLinkDropdownText: secondary.step12,
    hoverNavLinkDropdownBg: secondary.step4,
    hoverNavLinkDropdownBorder: secondary.step8,
    activeNavLinkDropdownBg: secondary.step9,
    activeNavLinkDropdownBorder: secondary.step6,
  },
  appSwitcher: AppSwitcherLight,
};
