---
name: Provide Feedback
description: Questions and general feedback goes here!
labels: ['feedback', 'beta']
body:
  - type: checkboxes
    attributes:
      label: App
      description: For which app do want to provide feedback?
      options:
        - label: '[Admin](https://admin.daohaus.fun)'
        - label: '[Summon](https://summon.daohaus.fun)'
        - label: '[Hub](https://hub.daohaus.fun)'
        - label: '[Toolbox](https://toolbox.daohaus.fun/)'
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: Feedback Type
      options:
        - label: Comments
        - label: Questions
        - label: Other
    validations:
      required: true
  - type: textarea
    attributes:
      label: Feedback
      description: Offer general feedback or feedback on a specific use case.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Screenshots and Context
      placeholder: |
        Add additional information that will help us understand your feedback.
        You can also add screenshots by pasting from your clipboard.
    validations:
      required: false
