name: Develop Setup

description: Setup Node.js, cache and install dependencies

inputs:
  node_version:
    description: Node.js version
    required: false
    default: '16'

runs:
  using: composite
  steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v2
      with:
        node-version: 16.x
        # This doesn't just set the registry url, but also sets
        # the right configuration in .npmrc that reads NPM token
        # from NPM_AUTH_TOKEN environment variable.
        # It actually creates a .npmrc in a temporary folder
        # and sets the NPM_CONFIG_USERCONFIG environment variable.
        registry-url: https://registry.npmjs.org
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    - name: Save kubeconfig
      run: doctl kubernetes cluster kubeconfig save daohaus-staging-nyc3-1653325548883
    - name: Create env file
      run: |
        touch .env
        echo NX_RIVET_KEY=${{ secrets.RIVET_KEY }}  >> .env
        echo VITE_RIVET_KEY=${{ secrets.RIVET_KEY }}  >> .env
        echo CERAMIC_NETWORK=testnet-clay  >> .env
        echo NODE_ENV=production  >> .env
    - run: yarn install
    - run: npm install -g nx
