import { amber, amberDark, indigo, indigoDark } from '@radix-ui/colors';
import { ButtonColorTargets } from '../../styled';

export const PrimaryDarkButton: ButtonColorTargets = {
  bg: amberDark.amber9,
  text: indigoDark.indigo1,
  border: amberDark.amber9,
  hoverBg: amberDark.amber10,
  hoverText: indigoDark.indigo1,
  hoverBorder: amberDark.amber10,
  focusBg: amberDark.amber10,
  focusText: indigoDark.indigo1,
  focusBorder: amberDark.amber11,
  activeBg: amberDark.amber9,
  activeText: indigoDark.indigo1,
  activeBorder: amberDark.amber9,
  disabledBg: amberDark.amber8,
  disabledText: indigoDark.indigo1,
  disabledBorder: amberDark.amber8,
};
export const SecondaryDarkButton: ButtonColorTargets = {
  bg: indigoDark.indigo4,
  text: indigoDark.indigo12,
  border: indigoDark.indigo4,
  hoverBg: indigoDark.indigo6,
  hoverText: indigoDark.indigo12,
  hoverBorder: indigoDark.indigo6,
  focusBg: indigoDark.indigo4,
  focusText: indigoDark.indigo12,
  focusBorder: indigoDark.indigo11,
  activeBg: indigoDark.indigo4,
  activeText: indigoDark.indigo12,
  activeBorder: indigoDark.indigo4,
  disabledBg: indigoDark.indigo3,
  disabledText: indigoDark.indigo8,
  disabledBorder: indigoDark.indigo4,
};
export const TertiaryDarkButton: ButtonColorTargets = {
  bg: 'transparent',
  text: amberDark.amber11,
  border: amberDark.amber9,
  hoverBg: indigoDark.indigo3,
  hoverText: amberDark.amber10,
  hoverBorder: amberDark.amber9,
  focusBg: 'transparent',
  focusText: amberDark.amber10,
  focusBorder: amberDark.amber12,
  activeBg: 'transparent',
  activeText: amberDark.amber11,
  activeBorder: amberDark.amber9,
  disabledBg: 'transparent',
  disabledText: amberDark.amber8,
  disabledBorder: amberDark.amber8,
};

export const PrimaryLightButton: ButtonColorTargets = {
  bg: amber.amber9,
  text: indigo.indigo12,
  border: amber.amber9,
  hoverBg: amber.amber10,
  hoverText: indigo.indigo12,
  hoverBorder: amber.amber10,
  focusBg: amber.amber10,
  focusText: indigo.indigo12,
  focusBorder: amber.amber11,
  activeBg: amber.amber9,
  activeText: indigo.indigo12,
  activeBorder: amber.amber9,
  disabledBg: amber.amber8,
  disabledText: indigo.indigo12,
  disabledBorder: amber.amber8,
};
export const SecondaryLightButton: ButtonColorTargets = {
  bg: indigo.indigo4,
  text: indigo.indigo12,
  border: indigo.indigo4,
  hoverBg: indigo.indigo6,
  hoverText: indigo.indigo12,
  hoverBorder: indigo.indigo6,
  focusBg: indigo.indigo4,
  focusText: indigo.indigo12,
  focusBorder: indigo.indigo11,
  activeBg: indigo.indigo4,
  activeText: indigo.indigo12,
  activeBorder: indigo.indigo4,
  disabledBg: indigo.indigo3,
  disabledText: indigo.indigo8,
  disabledBorder: indigo.indigo4,
};
export const TertiaryLightButton: ButtonColorTargets = {
  bg: 'transparent',
  text: amber.amber11,
  border: amber.amber9,
  hoverBg: indigo.indigo3,
  hoverText: amber.amber10,
  hoverBorder: amber.amber9,
  focusBg: 'transparent',
  focusText: amber.amber10,
  focusBorder: amber.amber12,
  activeBg: 'transparent',
  activeText: amber.amber11,
  activeBorder: amber.amber9,
  disabledBg: 'transparent',
  disabledText: amber.amber8,
  disabledBorder: amber.amber8,
};
